export const AUTH_LOGIN_INIT = "AUTH_LOGIN_INIT";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SEND_NEW_POST_TO_SERVER_INIT = "SEND_NEW_POST_TO_SERVER_INIT";
export const SEND_NEW_POST_TO_SERVER_SUCCESS =
    "SEND_NEW_POST_TO_SERVER_SUCCESS";
export const SEND_NEW_POST_TO_SERVER_FAIL = "SEND_NEW_POST_TO_SERVER_FAIL";

export const LIST_POSTS_TO_USER_DASHBOARD_INIT =
    "LIST_POSTS_TO_USER_DASHBOARD_INIT";
export const LIST_POSTS_TO_USER_DASHBOARD_SUCCESS =
    "LIST_POSTS_TO_USER_DASHBOARD_SUCCESS";
export const LIST_POSTS_TO_USER_DASHBOARD_FAIL =
    "LIST_POSTS_TO_USER_DASHBOARD_FAIL";

export const USER_PROFILE_VIEW_INIT = "USER_PROFILE_VIEW_INIT";
export const USER_PROFILE_VIEW_SUCCESS = "USER_PROFILE_VIEW_SUCCESS";
export const USER_PROFILE_VIEW_FAIL = "USER_PROFILE_VIEW_FAIL";

export const USER_PROFILE_EDIT_INIT = "USER_PROFILE_EDIT_INIT";
export const USER_PROFILE_EDIT_SUCCESS = "USER_PROFILE_EDIT_SUCCESS";
export const USER_PROFILE_EDIT_FAIL = "USER_PROFILE_EDIT_FAIL";

export const ADMIN_USER_LIST_VIEW_INIT = "ADMIN_USER_LIST_VIEW_INIT";
export const ADMIN_USER_LIST_VIEW_SUCCESS = "ADMIN_USER_LIST_VIEW_SUCCESS";
export const ADMIN_USER_LIST_VIEW_FAIL = "ADMIN_USER_LIST_VIEW_FAIL";

export const ADMIN_CREATE_USER_INIT = "ADMIN_CREATE_USER_INIT";
export const ADMIN_CREATE_USER_SUCCESS = "ADMIN_CREATE_USER_SUCCESS";
export const ADMIN_CREATE_USER_FAIL = "ADMIN_CREATE_USER_FAIL";

export const ADMIN_VIEW_ALL_POSTS_INIT = "ADMIN_VIEW_ALL_POSTS_INIT";
export const ADMIN_VIEW_ALL_POSTS_SUCCESS = "ADMIN_VIEW_ALL_POSTS_SUCCESS";
export const ADMIN_VIEW_ALL_POSTS_FAIL = "ADMIN_VIEW_ALL_POSTS_FAIL";
