export const AUTH_LOGIN_INIT = "AUTH_LOGIN_INIT";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SEND_NEW_POST_TO_SERVER_INIT = "SEND_NEW_POST_TO_SERVER_INIT";
export const SEND_NEW_POST_TO_SERVER_SUCCESS =
    "SEND_NEW_POST_TO_SERVER_SUCCESS";
export const SEND_NEW_POST_TO_SERVER_FAIL = "SEND_NEW_POST_TO_SERVER_FAIL";

export const LIST_POSTS_TO_USER_DASHBOARD_INIT =
    "LIST_POSTS_TO_USER_DASHBOARD_INIT";
export const LIST_POSTS_TO_USER_DASHBOARD_SUCCESS =
    "LIST_POSTS_TO_USER_DASHBOARD_SUCCESS";
export const LIST_POSTS_TO_USER_DASHBOARD_FAIL =
    "LIST_POSTS_TO_USER_DASHBOARD_FAIL";
